"""
Word Ladder Steps (hard) · patterns: bfs, shortest-path

Given a starting word, a target word, and a dictionary of allowed words,
transform the start into the target by changing one letter at a time. Every
intermediate word, and the target itself, must appear in the dictionary, and
all words share the same length. Return the number of words in the shortest
chain including both ends, or 0 when no chain exists.

Examples:

    Input:  start = hit, target = cog, words = [hot, dot, dog, lot, log, cog]
    Output: 5
    Why:    hit, hot, dot, dog, cog is five words long

    Input:  start = hit, target = cog, words = [hot, dot, dog]
    Output: 0
    Why:    the target is missing from the dictionary, so nothing can reach it

    Input:  start = a, target = c, words = [a, b, c]
    Output: 2
    Why:    edge case, single letters let the start reach the target directly

Approach:
    Words are nodes and single-letter edits are unweighted edges, so a
    breadth-first exploration finds the shortest chain. Neighbours are
    generated by substituting every letter at every position and keeping the
    results that exist in the dictionary, which is cheaper than comparing
    all pairs of words. Deleting a word on first arrival marks it visited
    and prevents the queue from revisiting it, since the first arrival is
    always the shortest. Time is O(N times L times 26) for N words of length
    L, and space is O(N times L).

The lesson behind it: Graphs You Never Build
    https://bytepatterns.com/learn/graphs/implicit-graph-bfs
    python graphs/14-implicit-graph-bfs.py

Try it first with progressive hints on the site:
    https://bytepatterns.com/practice/graphs/word-ladder-steps

Run it:  python problems/graphs/03-word-ladder-steps.py
"""


from collections import deque
from string import ascii_lowercase
def ladder_length(start, target, words):
    pool = set(words)
    if target not in pool: return 0  # an unreachable target ends it early
    q = deque([(start, 1)])          # word plus the chain length so far
    while q:
        word, steps = q.popleft()
        if word == target: return steps
        for i in range(len(word)):
            for ch in ascii_lowercase:        # try every single-letter edit
                nxt = word[:i] + ch + word[i+1:]
                if nxt in pool:
                    pool.remove(nxt)          # first arrival is the shortest
                    q.append((nxt, steps + 1))
    return 0


# ---------------------------------------------------------------------------
# Self-check: the example below prints the output its page on
# bytepatterns.com states, and `python run_all.py` fails if it ever drifts.

def check(value, expected):
    """Print the value, then assert it is what the lesson says it is."""
    print(value)
    assert value == expected, f"expected {expected!r}, got {value!r}"


if __name__ == "__main__":
    check(ladder_length("hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"]), 5)
    check(ladder_length("hit", "cog", ["hot", "dot", "dog"]), 0)
    check(ladder_length("a", "c", ["a", "b", "c"]), 2)
